/** ****************************************************************************
 * @brief Events generated by DAC module.
 *
 * The public events dac module generates.
 */

#ifndef FKMG_DAC_EVT_H
#define FKMG_DAC_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "id.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum DAC_Evt_Sig{
    k_DAC_Evt_Sig_Beg,                        // Inclusive
    k_DAC_Evt_Sig_Min = k_DAC_Evt_Sig_Beg,    // Inclusive
    k_DAC_Evt_Sig_1st = k_DAC_Evt_Sig_Beg,    // Inclusive

    k_DAC_Evt_Sig_Instance_Initialized = k_DAC_Evt_Sig_Beg,
    #if CONFIG_FKMG_DAC_SHUTDOWN_ENABLED
    k_DAC_Evt_Sig_Instance_Deinitialized,
    #endif
    k_DAC_Evt_Sig_TimerUp,                    //
    k_DAC_Evt_Sig_Write,                      // Write to DAC
         

    k_DAC_Evt_Sig_End,                        // Exclusive
    k_DAC_Evt_Sig_Max = k_DAC_Evt_Sig_End - 1,// Inclusive
    k_DAC_Evt_Sig_Lst = k_DAC_Evt_Sig_End - 1,// Inclusive
    k_DAC_Evt_Sig_Cnt = k_DAC_Evt_Sig_End
                      - k_DAC_Evt_Sig_Beg,	  // Inclusive
	k_DAC_Evt_Sig_Ivd = k_DAC_Evt_Sig_End
};

/* Forward references to prevent include interdependent items getting declared
 * out-of-order. */
struct DAC_Instance;

/* Data signal k_DAC_Evt_Sig_Instance_Initialized can generate. */
struct DAC_Evt_Data_Instance_Initialized{
    struct DAC_Instance * p_inst;
};

/* Data signal k_DAC_Evt_Sig_Changed can generate. */
struct DAC_Evt_Data_Timer_Up{
    enum DAC_Id id;
    uint32_t    val;
};

/* Events (i.e. signal + signal's data if any) that can be generated. */
struct DAC_Evt{
	enum DAC_Evt_Sig sig;
	union DAC_Evt_Data{
        struct DAC_Evt_Data_Instance_Initialized    initd;
        struct DAC_Evt_Data_Timer_Up                timup; 
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_DAC_EVT_H */
