/** ****************************************************************************
 * @brief Internal state machine events generated by USB.
 */

#ifndef FKMG_USB_SM_EVT_H
#define FKMG_USB_SM_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "../id.h"
#include "../instance_cfg.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum USB_SM_Evt_Sig{
    k_USB_SM_Evt_Sig_Beg,                           // Inclusive
    k_USB_SM_Evt_Sig_Min = k_USB_SM_Evt_Sig_Beg,    // Inclusive
    k_USB_SM_Evt_Sig_1st = k_USB_SM_Evt_Sig_Beg,    // Inclusive

	k_USB_SM_Evt_Sig_Init_Instance = k_USB_SM_Evt_Sig_Beg,
    #if CONFIG_FKMG_USB_ALLOW_SHUTDOWN
	k_USB_SM_Evt_Sig_Deinit_Instance,
    #endif
    k_USB_SM_Evt_Sig_End,                           // Exclusive
    k_USB_SM_Evt_Sig_Max = k_USB_SM_Evt_Sig_End - 1,// Inclusive
    k_USB_SM_Evt_Sig_Lst = k_USB_SM_Evt_Sig_End - 1,// Inclusive
    k_USB_SM_Evt_Sig_Cnt = k_USB_SM_Evt_Sig_End
                         - k_USB_SM_Evt_Sig_Beg,	// Inclusive
	k_USB_SM_Evt_Sig_Ivd = k_USB_SM_Evt_Sig_End
};

/* Data signal k_USB_SM_Evt_Sig_Init_Instance can generate. */
struct USB_SM_Evt_Sig_Init_Instance{
    struct USB_Instance_Cfg cfg;
};


/* Events (i.e. signal + signal's data if any) USB State Machine generates. */
struct USB_SM_Evt{
	enum USB_SM_Evt_Sig sig;
	union USB_SM_Evt_Data{
        struct USB_SM_Evt_Sig_Init_Instance  init_inst;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_USB_SM_EVT_H */
