/** ****************************************************************************
 * @brief Internal state machine events generated by DAC.
 */

#ifndef FKMG_DAC_SM_EVT_H
#define FKMG_DAC_SM_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "../id.h"
#include "../instance_cfg.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum DAC_SM_Evt_Sig{
    k_DAC_SM_Evt_Sig_Beg,                           // Inclusive
    k_DAC_SM_Evt_Sig_Min = k_DAC_SM_Evt_Sig_Beg,    // Inclusive
    k_DAC_SM_Evt_Sig_1st = k_DAC_SM_Evt_Sig_Beg,    // Inclusive

	k_DAC_SM_Evt_Sig_Init_Instance = k_DAC_SM_Evt_Sig_Beg,
    #if CONFIG_FKMG_DAC_ALLOW_SHUTDOWN
	k_DAC_SM_Evt_Sig_Deinit_Instance,
    #endif
	k_DAC_SM_Evt_Sig_XXX,

    k_DAC_SM_Evt_Sig_End,                           // Exclusive
    k_DAC_SM_Evt_Sig_Max = k_DAC_SM_Evt_Sig_End - 1,// Inclusive
    k_DAC_SM_Evt_Sig_Lst = k_DAC_SM_Evt_Sig_End - 1,// Inclusive
    k_DAC_SM_Evt_Sig_Cnt = k_DAC_SM_Evt_Sig_End
                         - k_DAC_SM_Evt_Sig_Beg,	// Inclusive
	k_DAC_SM_Evt_Sig_Ivd = k_DAC_SM_Evt_Sig_End
};

/* Data signal k_DAC_SM_Evt_Sig_Init_Instance can generate. */
struct DAC_SM_Evt_Sig_Init_Instance{
    struct DAC_Instance_Cfg cfg;
};

/* Data signal k_DAC_SM_Sig_XXX can generate. */
struct DAC_SM_Evt_Sig_Convert{
    enum DAC_Id id;
};

struct DAC_SM_Evt_Sig_Force_Change{
    enum DAC_Id id;
};


/* Events (i.e. signal + signal's data if any) DAC State Machine generates. */
struct DAC_SM_Evt{
	enum DAC_SM_Evt_Sig sig;
	union DAC_SM_Evt_Data{
        struct DAC_SM_Evt_Sig_Init_Instance  init_inst;
        struct DAC_SM_Evt_Sig_Convert        convert;
        struct DAC_SM_Evt_Sig_Force_Change   force_change;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_DAC_SM_EVT_H */
