/** ****************************************************************************
 * @brief Internal state machine events generated by pot.
 */

#ifndef FKMG_POT_SM_EVT_H
#define FKMG_POT_SM_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "../id.h"
#include "../instance_cfg.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum Pot_SM_Evt_Sig{
    k_Pot_SM_Evt_Sig_Beg,                           // Inclusive
    k_Pot_SM_Evt_Sig_Min = k_Pot_SM_Evt_Sig_Beg,    // Inclusive
    k_Pot_SM_Evt_Sig_1st = k_Pot_SM_Evt_Sig_Beg,    // Inclusive

	k_Pot_SM_Evt_Sig_Init_Instance = k_Pot_SM_Evt_Sig_Beg,
    #if CONFIG_FKMG_POT_ALLOW_SHUTDOWN
	k_Pot_SM_Evt_Sig_Deinit_Instance,
    #endif
	k_Pot_SM_Evt_Sig_Convert,
	k_Pot_SM_Evt_Sig_Force_Change,

    k_Pot_SM_Evt_Sig_End,                           // Exclusive
    k_Pot_SM_Evt_Sig_Max = k_Pot_SM_Evt_Sig_End - 1,// Inclusive
    k_Pot_SM_Evt_Sig_Lst = k_Pot_SM_Evt_Sig_End - 1,// Inclusive
    k_Pot_SM_Evt_Sig_Cnt = k_Pot_SM_Evt_Sig_End
                         - k_Pot_SM_Evt_Sig_Beg,	// Inclusive
	k_Pot_SM_Evt_Sig_Ivd = k_Pot_SM_Evt_Sig_End
};

/* Data signal k_Pot_SM_Evt_Sig_Init_Instance can generate. */
struct Pot_SM_Evt_Sig_Init_Instance{
    struct Pot_Instance_Cfg cfg;
};

/* Data signal k_Pot_SM_Sig_Convert can generate. */
struct Pot_SM_Evt_Sig_Convert{
    enum Pot_Id id;
};

/* Data signal k_Pot_SM_Sig_Force_Change can generate. */
struct Pot_SM_Evt_Sig_Force_Change{
    enum Pot_Id id;
};

/* Events (i.e. signal + signal's data if any) Pot State Machine generates. */
struct Pot_SM_Evt{
	enum Pot_SM_Evt_Sig sig;
	union Pot_SM_Evt_Data{
        struct Pot_SM_Evt_Sig_Init_Instance  init_inst;
        struct Pot_SM_Evt_Sig_Convert        convert;
        struct Pot_SM_Evt_Sig_Force_Change   force_change;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_POT_SM_EVT_H */
