/** ****************************************************************************
 * @brief Events generated by pot module.
 *
 * The public events pot module generates.
 */

#ifndef FKMG_POT_EVT_H
#define FKMG_POT_EVT_H

#ifdef __cplusplus
extern "C" {
#endif

/* *****************************************************************************
 * Includes
 */

#include <zephyr/kernel.h>

#include "id.h"

/* *****************************************************************************
 * Events
 */

/* Signals that can be generated as part of an event. */
enum Pot_Evt_Sig{
    k_Pot_Evt_Sig_Beg,                        // Inclusive
    k_Pot_Evt_Sig_Min = k_Pot_Evt_Sig_Beg,    // Inclusive
    k_Pot_Evt_Sig_1st = k_Pot_Evt_Sig_Beg,    // Inclusive

    k_Pot_Evt_Sig_Instance_Initialized = k_Pot_Evt_Sig_Beg,
    #if CONFIG_FKMG_POT_SHUTDOWN_ENABLED
    k_Pot_Evt_Sig_Instance_Deinitialized,
    #endif
    k_Pot_Evt_Sig_Changed, // Value changed

    k_Pot_Evt_Sig_End,                        // Exclusive
    k_Pot_Evt_Sig_Max = k_Pot_Evt_Sig_End - 1,// Inclusive
    k_Pot_Evt_Sig_Lst = k_Pot_Evt_Sig_End - 1,// Inclusive
    k_Pot_Evt_Sig_Cnt = k_Pot_Evt_Sig_End
                      - k_Pot_Evt_Sig_Beg,	  // Inclusive
	k_Pot_Evt_Sig_Ivd = k_Pot_Evt_Sig_End
};

/* Forward references to prevent include interdependent items getting declared
 * out-of-order. */
struct Pot_Instance;

/* Data signal k_Pot_Evt_Sig_Instance_Initialized can generate. */
struct Pot_Evt_Data_Instance_Initialized{
    struct Pot_Instance * p_inst;
};

/* Data signal k_Pot_Evt_Sig_Changed can generate. */
struct Pot_Evt_Data_Changed{
    enum Pot_Id id;
    uint32_t    val;
};

/* Events (i.e. signal + signal's data if any) that can be generated. */
struct Pot_Evt{
	enum Pot_Evt_Sig sig;
	union Pot_Evt_Data{
        struct Pot_Evt_Data_Instance_Initialized initd;
        struct Pot_Evt_Data_Changed              changed;
	}data;
};

#ifdef __cplusplus
}
#endif

#endif /* FKMG_POT_EVT_H */
